[package]
name = "callback"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# wit-bindgen = { version = "0.9" }
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", branch = "main" }
