[package]
name = "nvim-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nvim-sys = { workspace = true }
thiserror = "1.0.40"
